In [6]:
#solving equation using matices

import numpy as np
A=np.array([[2,1,1],[1,3,2],[2,1,2]])
B=np.array([180,300,240])
xyz=np.linalg.solve(A,B)
print(xyz)



[36. 48. 60.]


In [7]:
C=np.array([[5/4,-2/3],[1/4,5/3]]) #ANOTHER examples
D=np.array([3,6])
xy=np.linalg.solve(C,D)
xy


array([4., 3.])

In [8]:
#Generate matrix
E= np.arange(0,11,2) #create array using sacling 2 until 10
E



array([ 0,  2,  4,  6,  8, 10])

In [9]:
E.reshape(2,3)  #buat matix dri value di atas #pastikan array sesuai dgn matrix yg diiginkan 

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [10]:
A.transpose() #Transpose matrix A

array([[2, 1, 2],
       [1, 3, 1],
       [1, 2, 2]])

In [11]:
A1= np.arange(1,10).reshape(3,3) 
A1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
A2= np.arange(0,17,2).reshape(3,3)
A2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [13]:
#wrong style multiplication also can use np.dot(A1,A2)#
A3= A1*A2
A3

array([[  0,   4,  12],
       [ 24,  40,  60],
       [ 84, 112, 144]])

In [14]:
#matrix multiplication using dot()
A4= A1.dot(A2)
A4

array([[ 48,  60,  72],
       [102, 132, 162],
       [156, 204, 252]])

In [15]:
F=np.array([[2,3],[3,6]], dtype= complex) #matrix for complex number
F

array([[2.+0.j, 3.+0.j],
       [3.+0.j, 6.+0.j]])

In [16]:
zero_matrix= np.zeros((2,3)) #need to have double()#
print('zeros matrix= ')     #zeros matrix
zero_matrix

zeros matrix= 


array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
ones_matrix= np.ones((2,)) #need to have double()#
ones_matrix

array([1., 1.])

In [18]:
A12= np.add(A1,A2) #addition
A12

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

In [19]:
G=np.dot(A1,A2) #Multiplication
G

array([[ 48,  60,  72],
       [102, 132, 162],
       [156, 204, 252]])

In [20]:
print(np.max(G),np.min(G)) #MAX & MIN value

252 48


In [21]:
b= G.T   #transpose
b

array([[ 48, 102, 156],
       [ 60, 132, 204],
       [ 72, 162, 252]])

In [22]:
#There is extensive list of functions that can perform almost all operations on matrix
#1) .shape 2) .size 3).ndim 4) mean() 5) var() 6) std()#
# 7) flatten()#

In [33]:
G.shape
G.flatten()



array([ 48,  60,  72, 102, 132, 162, 156, 204, 252])